/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f23c952c-5099-41fe-a9ba-9d281ddccc88",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YTMaYISXr",
    "aws_user_pools_web_client_id": "133cr1o6pdjlno5ttkc8j7q5sd",
    "oauth": {}
};


export default awsmobile;
